### PR TITLE
Added plugin menu

### LINKED ISSUE #16: [Request] Plugin loading?
Currently i use smm for my skyrim mods. however skyrim requires some extra steps to actually enable the added files. an entry has to be added in an ini file and load order is a thing and all this other stuff. there is an external tool i use to manage this, but it would be neat if i could just go to a "plugins" page in the skyrim page in smm and select SkyMM-NX and enable it there. what im asking is for a way for people to write plugins for smm to add functionality that is specific to a game.

### PR DESCRIPTION
**Pull request by Witherking25**
closes #16

### CODE REVIEW

**Comment by nadrino** [comment]
Great addition!! Gonna check this soon :)

For the README, one could do a spoiler to hide the full text of the plugin source code example

**Comment by Witherking25** [comment]
done!

**Comment by Witherking25** [comment]
https://github.com/withertech/Sky-MM-NX-SMM

**Comment by Witherking25** [comment]
the original was console only

**Comment by nadrino** [comment]
Sorry for the late reply, I had my Switch sleeping in limbo du to a failed update... I'm gonna try it!

**Comment by nadrino** [comment]
Alright so I was able to see the .smm plugin in the GUI but when I click on it, SMM is just quitting. Did I miss a step?

**Comment by Witherking25** [comment]
uh
the way it loads the plugin is by setting the next load env to the path to the smm plugin so that NX-Hbloader loads the plugin instead of NX-Hbmenu and then quits SimpleModManager so it loads it.

**Comment by Witherking25** [comment]
it definitely works on my end on my switch. what plugin are you using? if the nro requires files next to it (eg in the switch folder) it will still look for those files in the switch folder and not next to the actual nro which is in the .plugins

**Comment by Witherking25** [comment]
Try this plugin. It links against my library that i made with some helper functions and it returns back to smm on exit if it detects if it was loaded as a plugin.
[SkyMM-NX.zip](https://github.com/nadrino/SimpleModManager/files/6052766/SkyMM-NX.zip)
extract it and put the smm in `sdmc:/mods/Skyrim/.plugins/`

**Comment by Witherking25** [comment]
the nro is just for if you want to try my fork of SkyMM-NX from NX-Hbmenu because mine has a proper gui :)

**Comment by Witherking25** [comment]
Is this going to get merged?

**Comment by nadrino** [comment]
Hi @Witherking25, yeah sorry for the enormous delay! I had a lot of work and didn't keep the developments. Actually I tried to update the GUI repo but they changed a lot of things, and I had to update (and understand) their new methods.

May be I will rollback to the previous version (since I didn't work on a separated branch... bad idea xD), and merge you plugin feature on the last version. Is it ok for you?

**Comment by Witherking25** [comment]
Sure!

**Comment by Witherking25** [comment]
Absolutely!

**Comment by Witherking25** [comment]
Also the updated borealis is incomplete. They don’t have lists and stuff yet. I would just stick with the old version until the new one matures more

**Comment by Witherking25** [comment]
merge?

**Comment by nadrino** [comment]
let's go :)

**Comment by Witherking25** [comment]
yay

**Comment by snoozbuster** [comment]
just FYI - pretty sure this PR screwed up the build. I'm not able to get master to build successfully, but if I revert the top merge commit I'm able to get it to build just fine. I think when these got merged, a bunch of stuff in the submodules got really out of whack.

**Comment by Witherking25** [comment]
What exactly seems to be the issue? It builds fine before he merged it on my end.

**Comment by snoozbuster** [comment]
I imagine it does - I haven’t pulled down your fork and tried to build it but my suspicion is that it does work. If you pull down my fork (which doesn’t include your merge), it should also build. But if I try to build master of this repo I get some errors about missing functions and definitions, and even some errors about undefined submodules - it looks like something went wrong in the merge, especially w.r.t the submodules. I wasn’t able to sort out exactly what happened, only figure out that if I reverted the merge commit at the head of master then it would build.

**Comment by Witherking25** [comment]
it seems to be an issue with tesla. they must have changed some things in libnx and the version of tesla i have in my fork doesn't use the updated api. updating the libtesla submodule should fix this

**Comment by Witherking25** [comment]
https://github.com/WerWolv/libtesla/issues/52

**Comment by Witherking25** [comment]
see #26

**Pull request merged**
